name: OntimeTop
version: '${project.version}'
main: dk.nydt.Main
api-version: 1.8
authors: [ Nydt, iskoldcool, Shad0wsense ]
description: Top 3 most ontime
website: mcstore.dk
commands:
  Ontime:
    description: gets ontime of player
  OntimeTop:
    description: gets the 5 most gaming players
